### PR TITLE
Potentially fixing the bug of incorrect deep_free

### LINKED ISSUE #4: seg fault on Raspberry Pi 3B
Raspberry Pi 3B: 32bit linux
2021-07-21-224636_1920x1080_scrot
[error.log](https://github.com/chinesebear/deepmem/files/6856699/error.log)

### PR DESCRIPTION
**Pull request by MMZK1526**
1. Store the offset between head and payload in a global variable.
2. Use this offset, not sizeof(), to get the right position of head.
3. The bug was originally reproducible on my 64bit mac, now it's fixed.
May require further testing on a 32bit machine as well.
4. Further fix a bug on the inconsistency on block_size that causes
a few bytes not to be freed in every cycle.
5. Known issue: fast_free causes segfault; fast_bins are always NULL.

### CODE REVIEW

File: include/deep_mem.h [hunk 1]
```diff
@@ -12,7 +12,7 @@
 #define P_FLAG_OFFSET (1) /* previous block is allocated */
 #define P_FLAG_MASK (0x00000002)
 #define BLOCK_SIZE_MULTIPLIER (3)
-#define BLOCK_SIZE_MASK (0xfffffff4)
+#define BLOCK_SIZE_MASK (0xfffffffc)
```
Comment (chinesebear) [inline include/deep_mem.h]: this bit mask error is root cause?

File: src/deep_mem.c [hunk 2]
```diff
@@ -207,40 +218,38 @@ deep_malloc_fast_bins (uint32_t size)
...
   pool->free_memory -= payload_size;
-
   return &ret->payload;
 }
 
 static void *
 deep_malloc_sorted_bins (uint32_t size)
 {
-  block_size_t aligned_size = ALIGN_MEM_SIZE (size + sizeof (block_head_t));
+  block_size_t aligned_size = ALIGN_MEM_SIZE (size + 4);
```
Comment (chinesebear) [inline src/deep_mem.c]: 4 is magic word. can you change with macro value?

File: src/deep_mem.c [hunk 3]
```diff
@@ -308,14 +313,17 @@ deep_free_sorted_bins (void *ptr)
     {
       block_size_t prev_size
           = block_get_size ((block_head_t *)(block - sizeof (block_head_t)));
+      
       the_other = get_block_by_offset (block, -((int32_t)prev_size));
+      
       _merge_into_single_block (the_other, block);
-
+puts("test");
```
Comment (chinesebear) [inline src/deep_mem.c]: puts() is necessary?

**Review by chinesebear — COMMENTED** [review]
some ques

File: include/deep_mem.h (hunk 1 above)
Comment (MMZK1526) [reply include/deep_mem.h]: No, but I've checked with Joey; this should be fffffffc

File: src/deep_mem.c (hunk 3 above)
Comment (MMZK1526) [reply src/deep_mem.c]: This and above are used during debugging; I'll change them back and remove unnecessary prints

File: include/deep_mem.h (hunk 1 above)
Comment (chinesebear) [reply include/deep_mem.h]: done!
